cc_library(
    name = "taskplanner",
    srcs = ["taskplanner.cpp", ],
    hdrs = ["taskplanner.hpp", ],
    deps = ["//common:common", 
            "@ffx//:ffx"],
    visibility = ["//visibility:public"],
)