cc_library(
    name = "cartesian",
    srcs = ["differentialkinematics.cpp",],
    hdrs = ["differentialkinematics.hpp",],
    deps = ["//common:common", "@fmt//:fmt", "@spdlog//:spdlog", "@gurobi//:gurobi", "@rbdl//:rbdl", ],
    visibility = ["//visibility:public"],
)