cc_library(
    name = "multibody",
    srcs = ["multibodyplant.cpp", "rbdlmultibody.cpp",],
    hdrs = ["multibodyplant.hpp", "rbdlmultibody.hpp",],
    deps = ["//common:common", "@fmt//:fmt", "@spdlog//:spdlog", "@rbdl//:rbdl", ],
    visibility = ["//visibility:public"],
)