cc_library(
    name = "camera",
    srcs = ["realsense.cpp", ],
    hdrs = ["realsense.hpp", ],
    deps = ["@librealsense//:librealsense",
            "@pcl//:pcl",
            "@boost//:boost",
            "@eigen//:eigen",
            "@flann//:flann",
            ],
    visibility = ["//visibility:public"],
)