cc_library(
    name = "camera",
    srcs = ["realsense.cpp",],
    hdrs = ["realsense.hpp",],
    deps = ["//common:common", "@fmt//:fmt", "@spdlog//:spdlog", "@librealsense//:librealsense"],
    visibility = ["//visibility:public"],
)