cc_library(
    name = "physics",
    srcs = ["world.cpp",],
    hdrs = ["world.hpp",],
    deps = ["//common:common", "@fmt//:fmt", "@spdlog//:spdlog", "@bullet//:bullet"],
    visibility = ["//visibility:public"],
)