cc_library(
    name = "arm",
    hdrs = ["config.hpp", "robotinterface.hpp", "urinterface.hpp"],
    srcs = ["urinterface.cpp", ],
    deps = ["@eigen//:eigen", 
            "//common:common", 
            "@urdriver//:urdriver"],
    visibility = ["//visibility:public"],
)