cc_library(
    name = "fastplanner",
    srcs = ["sweptvolume.cpp",],
    hdrs = ["sweptvolume.hpp",],
    deps = ["//common:common", 
            "//mathematics:mathematics", 
            "//visualization:visualization",
            "@ompl//:ompl",],
    visibility = ["//visibility:public"],
)