cc_library(
    name = "joystick",
    srcs = ["ps4.cpp",],
    hdrs = ["ps4.hpp", "ps4state.hpp",],
    deps = ["//common:common", "@fmt//:fmt", "@spdlog//:spdlog",  "@glfw//:glfw",],
    visibility = ["//visibility:public"],
)